-- FIX: Use the FRESH hash generated by YOUR backend
-- This hash was generated by YOUR BCryptPasswordEncoder for "Test@123"

UPDATE users
SET password = '$2a$10$QWJaYsgiAbGhiLrPaz7EPOzk6SMJ//AxhYZoohm6ZYpbd4t2Pxov.'
WHERE username = 'admin';

-- Verify the update
SELECT username, password, enabled, role
FROM users
WHERE username = 'admin';

